### ISSUE TITLE
Documentation Inconsistencies Tracker

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#1813]
##  **This Issue is to Track Documentation Inconsistencies in One Place.**

---

## 1. Issues Already Present

> Bugs/Other Inconsistencies

- [ ] Migrate Docs From Aboutcode
- [ ] Docs in Wiki Outdated [Add Disclaimer and Links to ReadTheDocs]
- [ ] Update Docs in Pypi Page
- [ ] Update README (mention ``pip install`` and Python 3 support)
- [ ] Check that all Links to Documentation in Various places point to ReadTheDocs

---

## 2. Issues after an Upgrade 

> Docs That Will be inconsistent after a new feature (which is currently WIP/requested)

- [ ] Including Python 3 in Installer [Issue](https://github.com/nexB/scancode-toolkit/issues/1703)

**Comment by AyanSinhaMahapatra** [comment]
This is now updated and has issues from https://github.com/nexB/aboutcode/issues/32 here. As that issue is being closed.

**Comment by chinyeungli** [comment]
For (1), The wiki page has been removed, and all documentation is now available on Read the Docs. Additionally, I’ve verified that all links in the README are correct.

For (2), I confirmed all the options can be found on RTD and have description of it. The `--reindex-licenses` is now `scancode-reindex-licenses` (https://scancode-toolkit.readthedocs.io/en/latest/rst_snippets/scancode-reindex-licenses.html#scancode-reindex-licenses-usage)

For (3), everything is closed except for #1031 and #1703
