### ISSUE TITLE
ScanCode Toolkit Documentation Roadmap

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#1824]
## GSoD 2019

> WIP @AyanSinhaMahapatra 

- [x] Distribute Docs and Requirements with ScanCode
- [ ] Migrate Docs From Aboutcode
- [ ] Getting Started for Newcomers
- [ ] Cookiecutter Plugin + Docs
- [ ] JSON Model (Autodoc)

## Roadmap Forward

- [ ] API (Importing ScanCode and using API to Scan) #1780

**Comment by chinyeungli** [comment]
@AyanSinhaMahapatra I am not sure what need to be done here. Can you elaborate a bit more?
