### ISSUE TITLE
Master issue: Improve ScanCode resources usage (CPU, RAM, Disk)

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3755]
It would be great to optimize resources usage.
In particular, these are the likely key hot spots:
- memory as used in license detection (was typically 0.8 GB now closer to 1.5GB per process)
- memory when return large JSON scans (which are all re-loaded in memory assembled from the cache)
- CPU when running copyright detection
- CPU when running license detection

Some related issues:
- [ ] https://github.com/nexB/scancode-toolkit/issues/2725
- [ ] https://github.com/nexB/scancode-toolkit/issues/1950
- [ ] https://github.com/nexB/scancode-toolkit/issues/3711
- [ ] https://github.com/nexB/scancode-toolkit/issues/1894
- [ ] https://github.com/nexB/scancode-toolkit/issues/3593
- [ ] https://github.com/nexB/scancode-toolkit/issues/2547
- [ ] https://github.com/nexB/scancode-toolkit/issues/1014
- [ ] https://github.com/nexB/scancode-toolkit/issues/1809
- [ ] https://github.com/nexB/scancode-toolkit/issues/3143

**Comment by pombredanne** [comment]
@tdruez can you reference related ScanCode.io issues
@JonoYang same on PurlDB?

**Comment by JonoYang** [comment]
@pombredanne I haven't seen this on the purldb side since we don't do much file scanning there. All file scanning is done by the scio workers. I think purldb mostly does license detection from text.

One of the immediate ideas that I have regarding the issue is that:

- we're creating a bunch of objects for large files somewhere and it's costing us a lot of memory to turn it into json
