### ISSUE TITLE
Add File-based user preferences and scan configuration

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#520]
When I run a scan I should be able to point to a a configuration file that would contain defaults for a scan as well as things such as in these tickets:
- [x] #36 : files to ignore in a scan 
- [x] #214 : license policy choices
- [ ] #377 : deduction and summarization preferences and options
- [x] #106 : define copyright holders to be skipped
- [x] #125 and #126 : set a preferred license choice when there is a choice or an "or later version" license 

This is also related to these tickets:
- [x] #209 : simplify CLI options
- [x] #280 ~~dejacode options~~
- [x] #262 ways and options to collect license texts
- [x] #384 Limit number of urls and emails reported in a scan for a single file
- [x] #447 stripping root directory or not
- [x] #464 ~~report only the first occurrence of a license~~

**Comment by pombredanne** [comment]
Since we only have #377 left open ... I am closing this in favor of #3639
