### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#552]
We need a plugin architecture such that it is easier to add new scanners, new formats and other features in a decoupled way.

At a high level, this is similar to Firefox, Chromium or Eclipse plugins.

The goal is to create a decoupled architecture such that output formatters and scanners (and in the future deduction tools) can:

1. be their own project/library and be plugged in ScanCode at installation time

2. for scanners and scan "pipeline processors" , they can possibly be coded in any language beside Python with Python being a special privileged language in any case. And accept an ABC data doc in and spit an ABC data out.

See for ABCD:
https://github.com/nexB/aboutcode/blob/a84e207bbe579dd9b419cc52bbfd00239f5beeb9/aboutcode-data/README.rst

For instance for packages scanners, a plugin approach such that new package manifests parsers are implemented as external libraries, eventually using different languages than Python to reuse the many parsers natively available (Ruby, Js, Java, etc) would make a lot of sense. .

Formatter/output should be the first to be implemented as plugins for a start, then eventually all scanners and more should be implemented as **plugins.** See #381 for format plugins. 

There stages where we can plugin things are, in this order of implementation priority:
- [x] output/formatters for JSON, HTML, etc . Tracked in #381 
- [x] post-scans hooks at the end of the scan, for instance for summarization/deduction for #377. Tracked in #699  
- [x] pre scan hook, before a scan (e.g. for instance archive extraction) #14
- [x] scan plugins "proper" that run a given scan. Tracked in #698. These may be specific to some file types or attributes and  may have dependencies on other scans. 

Other points:
- A plugin should be able to add new command line options even if minimally.

- The ability to have plugins in other languages than Python would be great: they would be spawned in their process and receive a path to scan and/or an ABC data packet and return an ABC data packet after having done their stuff.

- Some Python tools on Pypi such as pluggy, yapsy,  stevedore and the likes as well as possible click extensions may be candidate for this.

**Comment by pombredanne** [comment]
with #639 we now have support for pluggable output formats. This ticket should be used to track the high level feature completion. @yashdsaraf  please create separate ticket for each pluggable features (e.g. pre-scan, scan, post-scan)

**Comment by pombredanne** [comment]
With the latest merge of #885 this concludes the creation of plugins! Closing!
